import type { Metadata } from "next";
import "./globals.css";
import Nav from "./component/Nav";
import Header from "./component/header";
import styles from "@/app/styles/Home.module.css"




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Nav/>
        <div className={styles.container}>
          <main className={styles.main}>
            <Header/>
        {children}
        </main>
        </div>
      </body>
    </html>
  );
}
